server:
  port: 8040
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/notifications
    username: miguel
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: paymentConfirmation:com.miguel.raffles.Kafka.Payment.PaymentConfirmation,orderConfirmation:com.miguel.raffles.Kafka.Order.OrderConfirmation

  mail:
    host: smtp.gmail.com
    port: 587
    username: mlr.devs.97@gmail.com
    password: jnyl mytw lxbq ulrw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
